# Generated by Django 4.2.2 on 2023-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcer',
            field=models.CharField(default='X', max_length=100),
        ),
    ]
